In [25]:
import pandas
 
data = pandas.read_csv("Cleaned_License_Data.csv")
data

,Gender,Age Group_Teenager,Age Group_Young Adult,Race_Other,Race_White,Reactions,Applicant ID,Training,Signals,Yield,Speed Control,Night Drive,Road Signs,Steer Control,Mirror Usage,Confidence,Parking,Theory Test,Qualified
0,0.0,1.0,0.0,0.0,0.0,2.0,AID0084,Basic,34.57,41.63,7.63,29.69,40.85,46.52,32.70,48.91,45.14,40.53,0
1,1.0,1.0,0.0,1.0,0.0,0.0,AID0085,Basic,27.95,39.82,37.49,48.59,40.34,34.70,22.15,27.55,51.79,40.10,0
2,0.0,0.0,0.0,0.0,1.0,0.0,AID0396,NaN,44.77,48.45,18.09,36.98,56.57,34.48,46.02,46.07,30.86,59.63,0
3,1.0,0.0,1.0,1.0,0.0,2.0,AID0153,Basic,58.48,56.42,46.58,38.10,72.47,55.07,57.32,50.58,45.43,88.82,1
4,1.0,0.0,1.0,1.0,0.0,0.0,AID0009,NaN,35.59,41.80,45.71,32.72,10.09,34.31,27.35,36.64,31.94,64.57,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,1.0,1.0,0.0,1.0,0.0,2.0,AID0125,NaN,36.90,17.24,26.41,19.97,29.02,19.32,36.30,13.37,22.20,93.90,0
496,0.0,0.0,1.0,1.0,0.0,1.0,AID0410,Basic,38.47,51.61,59.91,51.37,47.32,56.25,66.14,45.03,56.45,91.05,0
497,1.0,0.0,0.0,0.0,0.0,1.0,AID0192,Advanced,56.72,90.42,61.26,89.93,51.31,56.75,78.39,74.84,67.31,97.69,1
498,0.0,0.0,0.0,0.0,0.0,2.0,AID0258,Advanced,75.06,81.75,49.93,54.18,59.30,68.53,54.77,55.68,78.93,65.79,1
499,0.0,1.0,0.0,1.0,0.0,1.0,AID0354,NaN,28.39,41.48,22.82,21.04,32.05,35.90,18.69,5.66,41.59,66.72,0

In [26]:
# Returns the total number of duplicate rows
duplicate_count = data.duplicated().sum()
print(f"Number of duplicate rows: {duplicate_count}")

Number of duplicate rows: 0

In [27]:
# LOOKING FOR MISSING VALUES
data.isnull().sum()

Gender                     0
Age Group_Teenager         0
Age Group_Young Adult      0
Race_Other                 0
Race_White                 0
Reactions                  0
Applicant ID               0
Training                 150
Signals                    0
Yield                      0
Speed Control              0
Night Drive                0
Road Signs                 0
Steer Control              0
Mirror Usage               0
Confidence                 0
Parking                    0
Theory Test                0
Qualified                  0
dtype: int64

In [28]:
# Reassigning the column with the filled values
data['Training'] = data['Training'].fillna('NA')

In [29]:
data.isnull().sum()

Gender                   0
Age Group_Teenager       0
Age Group_Young Adult    0
Race_Other               0
Race_White               0
Reactions                0
Applicant ID             0
Training                 0
Signals                  0
Yield                    0
Speed Control            0
Night Drive              0
Road Signs               0
Steer Control            0
Mirror Usage             0
Confidence               0
Parking                  0
Theory Test              0
Qualified                0
dtype: int64

In [30]:
# using the described function
data.describe()

,Gender,Age Group_Teenager,Age Group_Young Adult,Race_Other,Race_White,Reactions,Signals,Yield,Speed Control,Night Drive,Road Signs,Steer Control,Mirror Usage,Confidence,Parking,Theory Test,Qualified
count,500.000000,500.000000,500.0000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,0.484000,0.226000,0.4800,0.342000,0.332000,1.102000,48.525460,47.784000,47.931740,47.877760,47.793440,47.429480,48.157580,47.654440,48.452360,70.623380,0.498000
std,0.500244,0.418658,0.5001,0.474855,0.471403,0.710356,16.294927,16.062178,15.601242,15.302693,16.042885,15.580004,15.459866,16.056021,15.705702,17.864177,0.500497
min,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.770000,0.000000,0.000000,1.740000,0.000000,0.000000,0.000000,5.120000,0.000000,40.100000,0.000000
25%,0.000000,0.000000,0.0000,0.000000,0.000000,1.000000,38.097500,36.915000,37.297500,37.387500,36.547500,37.340000,38.355000,37.020000,37.460000,54.920000,0.000000
50%,0.000000,0.000000,0.0000,0.000000,0.000000,1.000000,48.415000,48.950000,49.405000,48.160000,49.310000,48.220000,48.360000,48.255000,49.400000,69.855000,0.000000
75%,1.000000,0.000000,1.0000,1.000000,1.000000,2.000000,59.357500,58.977500,58.392500,58.792500,58.772500,57.515000,58.795000,59.027500,59.262500,86.685000,1.000000
max,1.000000,1.000000,1.0000,1.000000,1.000000,2.000000,95.610000,94.410000,89.430000,89.930000,88.870000,89.240000,90.770000,90.280000,88.360000,99.750000,1.000000

In [31]:
# changing the qualified column to words as 1 is qualified and 0 is not qualified
data['Qualified'] = data['Qualified'].map({
    0: 'Not Qualified',
    1: 'Qualified'
})

# Machine lerning model
# separate the x and y 
array = data.values
# print(array)

# x shall represent the training data, which are the 18 inputs and the represent the inputs/features/labels
x = array[:, 0:18]   #[y,x]
# print(x)

# y represent the output/outcome/prediction .which are the types
y = array[:, 18]
# print(y)

# print(array)

In [32]:
# changing the yes and no to 1 and 0 respectively for the machine learning model
data['Training'] = data['Training'].replace({
    'Basic': 1,
    'Advanced': 2,
    'NA': 0
})

In [33]:
# split the data into training and testing data
from sklearn import model_selection

x_train, x_test, y_train, y_test = model_selection.train_test_split(x, y, test_size=0.3, random_state=42)

In [34]:
# Convert Back to DataFrame
import pandas as pd

x_train = pd.DataFrame(x_train, columns=data.columns[0:18])

In [35]:
print(type(x_train))
print(x_train[:5])

<class 'pandas.DataFrame'>
  Gender Age Group_Teenager Age Group_Young Adult Race_Other Race_White  \
0    0.0                0.0                   1.0        1.0        0.0
1    1.0                0.0                   1.0        0.0        0.0
2    0.0                0.0                   1.0        0.0        1.0
3    1.0                0.0                   1.0        0.0        1.0
4    1.0                0.0                   0.0        0.0        0.0

  Reactions Applicant ID  Training Signals  Yield Speed Control Night Drive  \
0       2.0      AID0425     Basic    48.3  28.63          50.9       33.04
1       1.0      AID0148     Basic   70.88  74.26         43.47       47.17
2       0.0      AID0111  Advanced   57.82  67.22         55.68       65.23
3       2.0      AID0230  Advanced   54.07  44.66         76.85        51.8
4       0.0      AID0115        NA   35.71  43.01         51.74       51.72

  Road Signs Steer Control Mirror Usage Confidence Parking Theory Test
0      58.13         32.98        38.34      33.08   53.83       86.28
1      65.86         45.66        39.94      60.21   36.22       40.76
2      55.69         73.99        54.44      62.82   46.85       89.03
3      66.17         49.78        90.77      65.43    48.0       71.39
4      33.85         47.07        56.81      67.73   49.91        49.1

In [36]:
# changing the female and male to 0 and 1 respectively for the machine learning model
x_train = pd.get_dummies(x_train)

In [37]:
# print(x_train.dtypes)

In [38]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)

In [39]:
# import one of the models
from sklearn.svm import SVC

model = SVC()
model.fit(x_train, y_train)

SVC()

In [40]:
data = data.drop('Applicant ID', axis=1)

In [41]:
y= data['Qualified']
x = data.drop('Qualified', axis=1)
# print(x)

In [42]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

x_train, x_test, y_train, y_test = model_selection.train_test_split(x, y, test_size=0.3, random_state=42)

In [43]:
model = SVC()
model.fit(x_train, y_train)

SVC()

In [44]:
# print(x_test)

In [45]:
# test the model to see what it would predict
predictions = model.predict(x_test)
print("Model predicted:", predictions)
print("We expected: ", y_test)

Model predicted: ['Qualified' 'Qualified' 'Qualified' 'Not Qualified' 'Qualified'
 'Qualified' 'Qualified' 'Qualified' 'Qualified' 'Qualified' 'Qualified'
 'Not Qualified' 'Qualified' 'Qualified' 'Not Qualified' 'Qualified'
 'Not Qualified' 'Not Qualified' 'Qualified' 'Not Qualified' 'Qualified'
 'Qualified' 'Not Qualified' 'Not Qualified' 'Qualified' 'Not Qualified'
 'Qualified' 'Qualified' 'Qualified' 'Qualified' 'Qualified' 'Qualified'
 'Qualified' 'Not Qualified' 'Not Qualified' 'Not Qualified' 'Qualified'
 'Qualified' 'Qualified' 'Not Qualified' 'Qualified' 'Not Qualified'
 'Not Qualified' 'Qualified' 'Qualified' 'Not Qualified' 'Not Qualified'
 'Qualified' 'Not Qualified' 'Qualified' 'Not Qualified' 'Not Qualified'
 'Not Qualified' 'Qualified' 'Qualified' 'Qualified' 'Qualified'
 'Qualified' 'Qualified' 'Not Qualified' 'Not Qualified' 'Qualified'
 'Qualified' 'Qualified' 'Qualified' 'Not Qualified' 'Qualified'
 'Qualified' 'Not Qualified' 'Qualified' 'Not Qualified' 'Qualified'
 'Not Qualified' 'Qualified' 'Qualified' 'Qualified' 'Not Qualified'
 'Not Qualified' 'Not Qualified' 'Not Qualified' 'Not Qualified'
 'Qualified' 'Not Qualified' 'Not Qualified' 'Qualified' 'Not Qualified'
 'Qualified' 'Qualified' 'Qualified' 'Not Qualified' 'Not Qualified'
 'Qualified' 'Not Qualified' 'Not Qualified' 'Not Qualified'
 'Not Qualified' 'Qualified' 'Qualified' 'Qualified' 'Qualified'
 'Not Qualified' 'Qualified' 'Not Qualified' 'Qualified' 'Not Qualified'
 'Qualified' 'Qualified' 'Qualified' 'Not Qualified' 'Qualified'
 'Qualified' 'Not Qualified' 'Not Qualified' 'Qualified' 'Qualified'
 'Not Qualified' 'Qualified' 'Qualified' 'Qualified' 'Not Qualified'
 'Qualified' 'Qualified' 'Not Qualified' 'Not Qualified' 'Qualified'
 'Qualified' 'Not Qualified' 'Qualified' 'Not Qualified' 'Qualified'
 'Qualified' 'Qualified' 'Qualified' 'Qualified' 'Not Qualified'
 'Not Qualified' 'Not Qualified' 'Qualified' 'Qualified' 'Not Qualified'
 'Qualified' 'Qualified' 'Qualified' 'Qualified' 'Not Qualified'
 'Qualified' 'Qualified' 'Qualified' 'Not Qualified' 'Not Qualified']
We expected:  361    Not Qualified
73         Qualified
374    Not Qualified
155    Not Qualified
104        Qualified
           ...
266        Qualified
23         Qualified
222        Qualified
261    Not Qualified
426    Not Qualified
Name: Qualified, Length: 150, dtype: str

In [46]:
# test the accuracy of the model
from sklearn.metrics import accuracy_score
print("Accuracy: ", accuracy_score(y_test, predictions))

Accuracy:  0.8066666666666666

In [47]:
Person = [[1.0,0.0,1.0,1.0,0.0,2.0,1,58.48,56.42,46.58,38.1,42.47,55.07,57.32,10.58,45.43,20.82]]
outcome = model.predict(Person)
print("The person is ", outcome)

The person is  ['Not Qualified']

c:\Users\Sylvia\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

In [48]:
# Imports Classification Models
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.svm import SVC

# Create an Empty List and append all models, Give the Models an alias Name
# i.e we called KNeighborsClassifier() alias KNC etc
models = []
models.append(('D Trees', DecisionTreeClassifier()))
models.append(('Gaussian', GaussianNB()))
models.append(('KNC', KNeighborsClassifier()))
models.append(('Random Forest', RandomForestClassifier()))
models.append(('Gradient Boosting', GradientBoostingClassifier()))
models.append(('Linear Disc', LinearDiscriminantAnalysis()))
models.append(('Support Machines', SVC(gamma = 'auto')))

# Import Cross Validation and KFOLD
from sklearn.model_selection import cross_val_score, KFold
# Create a for loop so that each model is tested in turn
for name, model in models:
            # Here we do a 10 split K-FOLD - We split our data into 10 Folds
            kfold = KFold(n_splits = 10, random_state=42, shuffle=True)

            # We Train and Test the current model in the Loop
            # Get the results for each Fold
            cv_results = cross_val_score(model, x_train, y_train, cv = kfold,
            scoring='accuracy')

            # Get the average of all Folds For that specific model in the Loop
            print(name, ' Results:= ', cv_results.mean())

D Trees  Results:=  0.7685714285714287
Gaussian  Results:=  0.8428571428571429
KNC  Results:=  0.78
Random Forest  Results:=  0.8257142857142856
Gradient Boosting  Results:=  0.8057142857142857
Linear Disc  Results:=  0.8285714285714285
Support Machines  Results:=  0.41999999999999993